superhero_database/superhero_database/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_database/superheroes/urls.py
from django.urls import path
from .import views


app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.detail, name='detail_superhero'),
    path('create/', views.create, name='create_superhero'),
    path('update/<int:superhero_id>/', views.update, name='update_superhero'),
    path('delete/<int:superhero_id>/', views.delete, name='delete_superhero')
]

superhero_database/superheroes/models.py
from django.db import models
# Create your models here.


class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    alternate_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_database/superheroes/views.py
from django.shortcuts import render
from .models import Superhero
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# Create your views here.


def index(request):
    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }
    return render(request, 'superheroes/index.html', context)


def detail(request, superhero_id):
    pick_superhero = Superhero.objects.get(pk=superhero_id)
    context = {
        'Superhero': pick_superhero
    }
    return render(request, 'superheroes/detail.html', context)


def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary_ability = request.POST.get('primary_ability')
        alternate_ability = request.POST.get('alternate_ability')
        catch_phrase = request.POST.get('catch_phrase')
        new_superhero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary_ability,
                                  alternate_ability=alternate_ability, catch_phrase=catch_phrase,)
        new_superhero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')


def delete(request, superhero_id):
    context = {}
    superhero = Superhero.objects.get(pk=superhero_id)
    if request.method == 'POST':
        superhero.delete()
        return HttpResponseRedirect(reverse('superheroes:index'))
    context['superhero'] = superhero
    return render(request, 'superheroes/delete.html', context)


def update(request, superhero_id):
    if request.method == 'POST':
        superhero = Superhero.objects.get(pk=superhero_id)
        superhero.name = request.POST.get('name')
        superhero.alter_ego = request.POST.get('alter_ego')
        superhero.primary_ability = request.POST.get('primary_ability')
        superhero.alternate_ability = request.POST.get('alternate_ability')
        superhero.catch_phrase = request.POST.get('catch_phrase')
        superhero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/update.html')

superhero_database/superheroes/templates/superheroes/create.html
<!doctype html>
<html lang="en">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
          crossorigin="anonymous"
    >
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,
          user-scalable=no,
          initial-scale=1.0,
          maximum-scale=1.0,
          minimum-scale=1.0"
    >
    <meta http-equiv="X-UA-Compatible"
          content="ie=edge"
    >
</head>
<body>
    <form action="{% url 'superheroes:create_superhero' %}" method="post">
        {% csrf_token %}
        Name:<input type="text" name="name" id="name"><br>
        Alter_ego:<input type="text" name="alter_ego" id="alter_ego"><br>
        Primary_ability:<input type="text" name="primary_ability" id="primary_ability"><br>
        Alternate_ability:<input type="text" name="alternate_ability" id="alternate_ability"><br>
        Catch_phrase:<input type="text" name="catch_phrase" id="catch_phrase"><br>
        <input type="submit" value="Add Superhero!">
    </form>
</body>
</html>

superhero_database/superheroes/templates/superheroes/delete.html
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
          crossorigin="anonymous"
    >
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,
          user-scalable=no, initial-scale=1.0,
          maximum-scale=1.0,
          minimum-scale=1.0"
    >
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete Superhero</title>
</head>
<body>
<form method ="post">
{% csrf_token %}
Sure you want to delete {{superhero}}?
<input type="submit" value = "Submit"/>
</form>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>
</body>
</html>

superhero_database/superheroes/templates/superheroes/detail.html
<!doctype html>
<html lang="en">
    <head>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <meta charset="UTF-8">
        <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
                <title>Superhero Details</title>
                <h1>Name</h1>
                <h3>{{Superhero.name}}</h3>
                <h1>Alter Ego</h1>
                <h3>{{Superhero.alter_ego}}</h3>
                <h1>Primary ability</h1>
                <h3>{{Superhero.primary_ability}}</h3>
                <h1>Alternate ability</h1>
                <h3>{{Superhero.alternate_ability}}</h3>
                <h1>Catch Phrase</h1>
                <h3>{{Superhero.catch_phrase}}</h3>
    </head>

    <body>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    </body>
</html>

superhero_database/superheroes/templates/superheroes/index.html
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
          crossorigin="anonymous"
    >
    <link rel="stylesheet"  >
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,
          user-scalable=no,
          initial-scale=1.0, maximum-scale=1.0,
          minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible"
          content="ie=edge"
    >

    <title>Superhero Index</title>
</head>
<body>
{% load static %}
<img src="{% static 'superheroes/spiderman.jpg' %}" alt="Spider Man">
    <ul>
        {% for Superhero in all_superheroes %}
        <li><h2>{{Superhero.name}}  </h2>
        <li><button type="button" class="btn"> <a href="{% url 'superheroes:detail_superhero' Superhero.id %}"> Superhero Details</a></button></li>
        <li> <button type="button" class="btn"><a href="{% url 'superheroes:update_superhero' Superhero.id %}">Update Superhero</a></button></li>
        <li><button type="button" class="btn"><a href="{% url 'superheroes:delete_superhero' Superhero.id %}">Delete Superhero</a></button></li>
        {% endfor %}
        <li> <button type="button" class="btn"><a href="{% url 'superheroes:create_superhero' %}"> Create a New Superhero</a></button></li>
    </ul>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

superhero_database/superheroes/templates/superheroes/update.html
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
          rel="styleSheet.css"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6"
          crossorigin="anonymous"
    >
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width,
          user-scalable=no,
          initial-scale=1.0,
          maximum-scale=1.0,
          minimum-scale=1.0"
    >
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Update Superhero</title>
</head>
<body>
<form method="post">
     {% csrf_token %}
    Name:<input type="text" name="name" id="name"><br>
    Alter Ego:<input type="text" name="alter_ego" id="alter_ego"><br>
    Primary Ability:<input type="text" name="primary_ability" id="primary_ability"><br>
    Alternate Ability:<input type="text" name="alternate_ability" id="alternate_ability"><br>
    Catch Phrase:<input type="text" name="catch_phrase" id="catch_phrase"><br>
    <input type="submit" value="Update Superhero">
</form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous">
    </script>
</body>
</html>